### ISSUE TITLE
TOTP: Cannot regenerate secret key

### ISSUE THREAD

**Issue by stephenharris** [georgestephanis/two-factor#138]
There doesn't seem to be away of regenerating a secret key for the TOTP.

If a device is lost you should be able to regenerate a new key so that device cannot be used to obtain access to the site.

**Comment by stephenharris** [comment]
There appears to be a branch for this: https://github.com/georgestephanis/two-factor/tree/add/totp-ajax (but it is currently stale).

**Comment by stefan2904** [comment]
This bug is still present, right?

Steps to reproduce:

1. enable and configure TOTP (e.g. with Google Authenticator)
2. get a new phone -> disable TOTP for now (before trashing the old phone)
3. re-enable TOTP -> no way to configure new phone, clicking on "View Options →" just says "Enabled"

![20180302_selection_02](https://user-images.githubusercontent.com/527767/36908257-0a058f6e-1e3b-11e8-8677-68c9ad744b5d.png)

I think it should be possible to add/remove multiple TOTPs, as it is possible to add multiple Security Keys?

**Comment by kasparsd** [comment]
Also reported here https://wordpress.org/support/topic/delete-existing-totp/
