### ISSUE TITLE
U2F works for only one security key.

### ISSUE THREAD

**Issue by dseomn** [georgestephanis/two-factor#193]
I'm using WordPress 4.8.1, Two Factor 0.1-dev-20170603, and Firefox with the U2F plugin. The first security key I registered works fine. I was able to register the other keys, but neither of them are able to log in. The login page just keeps asking me to touch the key again. The keys all work fine with other sites.

**Comment by WM4362** [comment]
I'm experiencing similar symptoms in that none of my 3 (previously working) U2F Keys are working on my Firefox 52.3.0 (32-bit)/Debian 8 Laptop - site is also WordPress 4.8.1, Two Factor Version 0.1-dev-20170603. It has been a good few months since I last used them on Firefox, but all three keys are still working fine on Chrome. 

And the Keys/Firefox U2F Plugin are tested and working fine - I used them to login to Github to make this comment! :-)

I can't find anything in logs to suggest what the issue may be, but I'd be happy to help troubleshoot.

**Comment by kasparsd** [comment]
I could replicate the issue using Firefox 55.0.3 on OS X while everything works as expected with Chrome. I'm not sure what the Firefox extension does differently.
