### ISSUE TITLE
Two Sessions with this plugin (BUG)

### ISSUE THREAD

**Issue by Milor123** [georgestephanis/two-factor#204]
Hi guys, I've seen that when use this plugin for login (with google authenticator), the plugin generates another session, in the same time.

Why? It only must generate one session not two.
Surely could be a bug.. 
Thank you very much.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @Milor123!

Here is how it works:

1. We first hook into the [`wp_login` action](https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/user.php#L104) and check if the user has two-factor enabled:

https://github.com/georgestephanis/two-factor/blob/24fbb1d63d1c1583259cfe7d65f137f439ae18c8/class.two-factor-core.php#L227-L236

This happens only if the regular username and password were correct.

2. We clear the authentication cookie because we need to verify the second factor:

https://github.com/georgestephanis/two-factor/blob/24fbb1d63d1c1583259cfe7d65f137f439ae18c8/class.two-factor-core.php#L534

3. We validate the second factor and issue another authentication cookie:

https://github.com/georgestephanis/two-factor/blob/211e9576d603a9ce445d722f6419d12f4e3db8a5/class.two-factor-core.php#L534

Is there a better way to do this?

Does it cause any issues with your particular implementation?

**Comment by Milor123** [comment]
Hi @kasparsd, really I have the plugin without changes, I've tested disable the plugin and then authenticate without him, as a consequence to deactivate it, now the wordpress only create a session (not two), by this reason I said that is a bug plugin.

Also I've test other browser (with all clear -> cookies, data... etc)
but it only happens when I activate this plugin

What do you think that could show to you for search the error?
Some log of debug file or something? (I am beginer in this, but surely you could guide me)
