### ISSUE TITLE
Implemenation of wp_login hook

### ISSUE THREAD

**Issue by neoxx** [georgestephanis/two-factor#229]
Hi,

Thanks for this great security plugin. :)

I use it together with https://wordpress.org/plugins/ninjafirewall/ on all my sites.

NinjaFirewall triggers an email on successful login via the _wp_login_ hook. Unfortunately the _exit_ in Two-Factor's _wp_login_ implementation at https://github.com/georgestephanis/two-factor/blob/master/class.two-factor-core.php#L235 does prevent NinjaFirewall from handling the notification mail correctly.

The plugin author of NinjaFirewall suggested that Two-Factor should execute it's _wp_login_ call earlier and remove the exit. Would that be possible?

My Best,
Berny

**Comment by kasparsd** [comment]
I agree, the use of `wp_login` hook isn't appropriate in the two-factor plugin, especially when combined with `exit`. Unfortunately, changing it to another approach requires a lot of work.

Removing `exit` isn't possible because we need to essentially stop the default WP login process after a successful login to clear the login cookie and ask for the second factor.

**Comment by neoxx** [comment]
Fyi, this issue has been resolved by changing the priority of NinjaFirewall's `wp_login` hook. (cf. new constant `NFW_LOGINHOOK`, [NinjaFirewall (WP+/WP) v4.2.2](https://blog.nintechnet.com/nintechnet-changelog/).

My Best,
Berny
