### ISSUE TITLE
FIDO (U2F) on multisite needs a key for every subsite

### ISSUE THREAD

**Issue by holzhannes** [georgestephanis/two-factor#302]
I am using my Yubikey on a wordpress multisite which has different domains for each subsite of the multisite. If i try to login as a superadmin on a subsite my Yubikey U2F is only working if I add a key for every subsite. TOTP is working also for every subsite.

**Comment by kasparsd** [comment]
Yeah, I'm having the same problem. The limitation is caused by to the FIDO protocol which ties each secret to an `AppID` which maps to a hostname of the site:

https://github.com/georgestephanis/two-factor/blob/ab8d6510a17606b200d1e44a603c13b5014bac52/providers/class.two-factor-fido-u2f.php#L108-L116

[FIDO defines Application Facets](https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-appid-and-facets-ps-20141009.html) but those are restricted to the same top-level domain, see https://github.com/georgestephanis/two-factor/issues/102#issuecomment-449560179 so they would't work with multiple domain names.

Not sure there is a way to make it work with WebAuthn.

**Comment by kasparsd** [comment]
> TOTP is working also for every subsite.

That's because it uses the same secret from the shared user meta for all sites in a network:

https://github.com/georgestephanis/two-factor/blob/ab8d6510a17606b200d1e44a603c13b5014bac52/providers/class.two-factor-totp.php#L169-L171
