### ISSUE TITLE
When someone selects a method as `Primary` it should always be `Enabled` too.

### ISSUE THREAD

**Issue by georgestephanis** [georgestephanis/two-factor#52]
When it is set as primary, toggle the linked Enabled checkbox to on.

**Comment by shield-9** [comment]
When every time changed (I feel this is too noisy):
```javascript
$(':radio[name="_two_factor_provider"]').change( function() {
	$(':checkbox[name="_two_factor_enabled_providers\\[\\]"]')
		.filter('[value="' + this.value + '"]')
		.prop('checked', true);
});
```

Or when submit:
```javascript
$('#your-profile').submit(function(){
	$(':checkbox[name="_two_factor_enabled_providers\\[\\]"]')
		.filter('[value="' + $(':radio[name="_two_factor_provider"]:checked').val() + '"]')
		.prop('checked', true);
});
```

I think the latter is better.

**Comment by aaroncampbell** [comment]
Is there any reason we don't just do this in the PHP?

**Comment by valendesigns** [comment]
This is for when someone is selecting the primary provider in their profile, correct?

**Comment by aaroncampbell** [comment]
Yes. There are checkboxes for "enabled" and radio buttons to choose "primary". The problem is that you can set TOTP to primary but only check the "enabled" box next to email (or anything similar). Since these settings are only saved when they're submitted, I think we use PHP to add `$_POST[ self::PROVIDER_USER_META_KEY ]` to `$enabled_providers` before we save it.
