### ISSUE TITLE
QR code notice displays when saving FIDO as the primary provider

### ISSUE THREAD

**Issue by valendesigns** [georgestephanis/two-factor#77]
> Two Factor Authentication not activated, you must specify authcode to ensure it is properly set up. Please re-scan the QR code and enter the code provided by your application.

**Comment by aaroncampbell** [comment]
Does this happen only when the TOTP checkbox is set to enabled? If so, I would think that's expected. Basically, you have it "enabled" and not set up, but you didn't enter a valid code when you updated your profile, which is the fallback for no JS.

If it happens when the enabled checkbox is NOT checked for TOTP, we should probably add a check for that.

**Comment by valendesigns** [comment]
I have both primary and enabled set to FIDO U2F, though I just discovered it's not specific to any one provider. I get a nag regardless of the provider or if I'm trying to set that provider as enabled or primary. So I just set Dummy Method as the enabled/primary provider and then just as primary and I see the nag in both situations.

**Comment by aaroncampbell** [comment]
Okay. My time is going to be really tight for the next couple weeks probably (my brother-in-law broke his back Saturday and has surgery tomorrow, and I have WordCamp Toronto this weekend), so if anyone else wants to take this, go for it.

Basically, I think we need to test to make sure the TOTP "enabled" checkbox is checked (in $_POST when not DOING_AJAX) before we test the code and throw the error to the user.

**Comment by lmartins** [comment]
Just updated to the latest version of the plugin, and tried to enable with only Email authentication enabled and still got this error.
